### ISSUE TITLE
User Story: AI Diffuculty

### ISSUE THREAD

**Issue by AlanAlper** [cse442-fall-2019-offering/442projects-cse-442-nerds-lmao#10]
As a player, I want a variety of AI difficulties so I can adjust based on how much I want to be challenged.

Tasks:
Create AI algorithms
Connect difficulty selection with corresponding AI algorithm

Acceptance Test:
1) Open the game.
2) Start a new level (by pressing "Play" on Main Menu and pressing "New Game" on Play Menu).
3) Observe the frequency of enemy spawns  and their health/speed throughout the level.
3) Exit the level to main menu.
4) Press "Settings"
5) Using the "Difficulty" drop box change difficulty.
6) Go back to main menu using the "Back" button.
7) Start a new level (by pressing "Play" on Main Menu and pressing "New Game" on Play Menu).
8) Observe the difference in frequency of enemy spawns  and their health/speed throughout the level.

**Comment by TracyZheng22** [comment]
Tasks:
-Implement (and decide) button in home menu/GUI on different difficulties.
-Decide how many modes there'll be (Example: Easy, Normal, Hard, etc.)
-To balance this out, the game should give out bigger rewards for bigger the difficulty.
