### ISSUE TITLE
[Sprint 2] Task: Create In-Game Currency

### ISSUE THREAD

**Issue by AlanAlper** [cse442-fall-2019-offering/442projects-cse-442-nerds-lmao#17]
Task:
Create in-game currency (Gold) by adding a "money" attribute to the player.

Task test 1:
1) Open the game.
2) Start a test level (by pressing "Play" on Main Menu and pressing "New Game" on Play Menu).
3) Observe the existence of an in-game currency on the bottom right of the screen. (In specific, the in game currency is gold and will be shown in the format of Gold: $325)

Task test 2:
1) Open Unity.
2) Load the project.
3) On the bottom-left corner there are the project folders.
4) Click Assets directory and then Scripts directory.
5) The script named "PlayerStats.cs" will include money attribute for the player.

**Comment by TracyZheng22** [comment]
Tasks:
-Implement Reward System 
a) What can the user get out of finishing a game/round?
b) What can the user spend it on?
c) Emphasis on the rewards
